[project]
name = "dz-catalog-analysis-naumov-m26-555"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mihail Naumov", email = "mi-n@list.ru" }
]
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []
